# Generated by Django 3.2.5 on 2022-08-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.BigIntegerField()),
                ('ville', models.CharField(max_length=150)),
                ('code_postale', models.IntegerField()),
                ('adresse', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulaire', models.CharField(max_length=150)),
                ('montant', models.FloatField()),
                ('numero', models.BigIntegerField()),
                ('expiration', models.CharField(max_length=30)),
                ('cryptogramme', models.CharField(max_length=150)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identitee.identitee')),
            ],
        ),
    ]
