# Generated by Django 3.2.5 on 2022-08-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0002_alter_identitee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitee',
            old_name='code_postale',
            new_name='code_postal',
        ),
    ]
