# Generated by Django 3.2.5 on 2022-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0003_rename_code_postale_identitee_code_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitee',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
