# Generated by Django 3.2.5 on 2022-08-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0009_alter_card_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='numero',
            new_name='num',
        ),
    ]
