# Generated by Django 3.2.5 on 2022-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0011_rename_card_id_card_identitee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='num',
            field=models.CharField(max_length=50),
        ),
    ]
