# Generated by Django 3.2.5 on 2022-08-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0012_alter_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='identitee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identitee.identitee'),
        ),
    ]
