# Generated by Django 3.2.5 on 2022-08-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identitee', '0013_alter_card_identitee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='num',
            new_name='numero',
        ),
    ]
